kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "nginx.fullname" . }}-maind
  labels:
    {{- include "nginx.labels" . | nindent 4 }}
data:
  {{- (tpl (.Files.Glob "main.d/*.conf").AsConfig . ) | nindent 2 }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "nginx.fullname" . }}-confd
  labels:
    {{- include "nginx.labels" . | nindent 4 }}
data:
  {{- (tpl (.Files.Glob "conf.d/*.conf").AsConfig . ) | nindent 2 }}
